export const COUNTRIES = [
    { name: 'Afghanistan', code: 'AF', dial_code: '+93', flag: '🇦🇫', nationality: 'Afghan', digits: 9 },
    { name: 'Albania', code: 'AL', dial_code: '+355', flag: '🇦🇱', nationality: 'Albanian', digits: 9 },
    { name: 'Algeria', code: 'DZ', dial_code: '+213', flag: '🇩🇿', nationality: 'Algerian', digits: 9 },
    { name: 'Andorra', code: 'AD', dial_code: '+376', flag: '🇦🇩', nationality: 'Andorran', digits: 6 },
    { name: 'Angola', code: 'AO', dial_code: '+244', flag: '🇦🇴', nationality: 'Angolan', digits: 9 },
    { name: 'Antigua and Barbuda', code: 'AG', dial_code: '+1-268', flag: '🇦🇬', nationality: 'Antiguan/Barbudan', digits: 7 },
    { name: 'Argentina', code: 'AR', dial_code: '+54', flag: '🇦🇷', nationality: 'Argentine', digits: 10 },
    { name: 'Armenia', code: 'AM', dial_code: '+374', flag: '🇦🇲', nationality: 'Armenian', digits: 8 },
    { name: 'Australia', code: 'AU', dial_code: '+61', flag: '🇦🇺', nationality: 'Australian', digits: 9 },
    { name: 'Austria', code: 'AT', dial_code: '+43', flag: '🇦🇹', nationality: 'Austrian', digits: 10 },
    { name: 'Azerbaijan', code: 'AZ', dial_code: '+994', flag: '🇦🇿', nationality: 'Azerbaijani', digits: 9 },
    { name: 'Bahamas', code: 'BS', dial_code: '+1-242', flag: '🇧🇸', nationality: 'Bahamian', digits: 7 },
    { name: 'Bahrain', code: 'BH', dial_code: '+973', flag: '🇧🇭', nationality: 'Bahraini', digits: 8 },
    { name: 'Bangladesh', code: 'BD', dial_code: '+880', flag: '🇧🇩', nationality: 'Bangladeshi', digits: 10 },
    { name: 'Barbados', code: 'BB', dial_code: '+1-246', flag: '🇧🇧', nationality: 'Barbadian', digits: 7 },
    { name: 'Belarus', code: 'BY', dial_code: '+375', flag: '🇧🇾', nationality: 'Belarusian', digits: 9 },
    { name: 'Belgium', code: 'BE', dial_code: '+32', flag: '🇧🇪', nationality: 'Belgian', digits: 9 },
    { name: 'Belize', code: 'BZ', dial_code: '+501', flag: '🇧🇿', nationality: 'Belizean', digits: 7 },
    { name: 'Benin', code: 'BJ', dial_code: '+229', flag: '🇧🇯', nationality: 'Beninese', digits: 8 },
    { name: 'Bhutan', code: 'BT', dial_code: '+975', flag: '🇧🇹', nationality: 'Bhutanese', digits: 8 },
    { name: 'Bolivia', code: 'BO', dial_code: '+591', flag: '🇧🇴', nationality: 'Bolivian', digits: 9 },
    { name: 'Bosnia and Herzegovina', code: 'BA', dial_code: '+387', flag: '🇧🇦', nationality: 'Bosnian', digits: 8 },
    { name: 'Botswana', code: 'BW', dial_code: '+267', flag: '🇧🇼', nationality: 'Motswana', digits: 8 },
    { name: 'Brazil', code: 'BR', dial_code: '+55', flag: '🇧🇷', nationality: 'Brazilian', digits: 11 },
    { name: 'Brunei', code: 'BN', dial_code: '+673', flag: '🇧🇳', nationality: 'Bruneian', digits: 7 },
    { name: 'Bulgaria', code: 'BG', dial_code: '+359', flag: '🇧🇬', nationality: 'Bulgarian', digits: 9 },
    { name: 'Burkina Faso', code: 'BF', dial_code: '+226', flag: '🇧🇫', nationality: 'Burkinabé', digits: 8 },
    { name: 'Burundi', code: 'BI', dial_code: '+257', flag: '🇧🇮', nationality: 'Burundian', digits: 8 },
    { name: 'Cambodia', code: 'KH', dial_code: '+855', flag: '🇰🇭', nationality: 'Cambodian', digits: 8 },
    { name: 'Cameroon', code: 'CM', dial_code: '+237', flag: '🇨🇲', nationality: 'Cameroonian', digits: 9 },
    { name: 'Canada', code: 'CA', dial_code: '+1', flag: '🇨🇦', nationality: 'Canadian', digits: 10 },
    { name: 'Cape Verde', code: 'CV', dial_code: '+238', flag: '🇨🇻', nationality: 'Cape Verdean', digits: 7 },
    { name: 'Central African Republic', code: 'CF', dial_code: '+236', flag: '🇨🇫', nationality: 'Central African', digits: 8 },
    { name: 'Chad', code: 'TD', dial_code: '+235', flag: '🇹🇩', nationality: 'Chadian', digits: 8 },
    { name: 'Chile', code: 'CL', dial_code: '+56', flag: '🇨🇱', nationality: 'Chilean', digits: 9 },
    { name: 'China', code: 'CN', dial_code: '+86', flag: '🇨🇳', nationality: 'Chinese', digits: 11 },
    { name: 'Colombia', code: 'CO', dial_code: '+57', flag: '🇨🇴', nationality: 'Colombian', digits: 10 },
    { name: 'Comoros', code: 'KM', dial_code: '+269', flag: '🇰🇲', nationality: 'Comoran', digits: 7 },
    { name: 'Congo (Brazzaville)', code: 'CG', dial_code: '+242', flag: '🇨🇬', nationality: 'Congolese', digits: 9 },
    { name: 'Congo (Kinshasa)', code: 'CD', dial_code: '+243', flag: '🇨🇩', nationality: 'Congolese', digits: 9 },
    { name: 'Costa Rica', code: 'CR', dial_code: '+506', flag: '🇨🇷', nationality: 'Costa Rican', digits: 8 },
    { name: 'Croatia', code: 'HR', dial_code: '+385', flag: '🇭🇷', nationality: 'Croat', digits: 8 },
    { name: 'Cuba', code: 'CU', dial_code: '+53', flag: '🇨🇺', nationality: 'Cuban', digits: 8 },
    { name: 'Cyprus', code: 'CY', dial_code: '+357', flag: '🇨🇾', nationality: 'Cypriot', digits: 8 },
    { name: 'Czech Republic', code: 'CZ', dial_code: '+420', flag: '🇨🇿', nationality: 'Czech', digits: 9 },
    { name: 'Denmark', code: 'DK', dial_code: '+45', flag: '🇩🇰', nationality: 'Dane', digits: 8 },
    { name: 'Djibouti', code: 'DJ', dial_code: '+253', flag: '🇩🇯', nationality: 'Djiboutian', digits: 8 },
    { name: 'Dominica', code: 'DM', dial_code: '+1-767', flag: '🇩🇲', nationality: 'Dominican', digits: 7 },
    { name: 'Dominican Republic', code: 'DO', dial_code: '+1-809', flag: '🇩🇴', nationality: 'Dominican', digits: 7 },
    { name: 'East Timor', code: 'TL', dial_code: '+670', flag: '🇹🇱', nationality: 'East Timorese', digits: 7 },
    { name: 'Ecuador', code: 'EC', dial_code: '+593', flag: '🇪🇨', nationality: 'Ecuadorian', digits: 9 },
    { name: 'Egypt', code: 'EG', dial_code: '+20', flag: '🇪🇬', nationality: 'Egyptian', digits: 10 },
    { name: 'El Salvador', code: 'SV', dial_code: '+503', flag: '🇸🇻', nationality: 'Salvadoran', digits: 8 },
    { name: 'Equatorial Guinea', code: 'GQ', dial_code: '+240', flag: '🇬🇶', nationality: 'Equatorial Guinean', digits: 9 },
    { name: 'Eritrea', code: 'ER', dial_code: '+291', flag: '🇪🇷', nationality: 'Eritrean', digits: 7 },
    { name: 'Estonia', code: 'EE', dial_code: '+372', flag: '🇪🇪', nationality: 'Estonian', digits: 7 },
    { name: 'Eswatini', code: 'SZ', dial_code: '+268', flag: '🇸🇿', nationality: 'Swazi', digits: 8 },
    { name: 'Ethiopia', code: 'ET', dial_code: '+251', flag: '🇪🇹', nationality: 'Ethiopian', digits: 9 },
    { name: 'Fiji', code: 'FJ', dial_code: '+679', flag: '🇫🇯', nationality: 'Fijian', digits: 7 },
    { name: 'Finland', code: 'FI', dial_code: '+358', flag: '🇫🇮', nationality: 'Finn', digits: 9 },
    { name: 'France', code: 'FR', dial_code: '+33', flag: '🇫🇷', nationality: 'French', digits: 9 },
    { name: 'Gabon', code: 'GA', dial_code: '+241', flag: '🇬🇦', nationality: 'Gabonese', digits: 7 },
    { name: 'Gambia', code: 'GM', dial_code: '+220', flag: '🇬🇲', nationality: 'Gambian', digits: 7 },
    { name: 'Georgia', code: 'GE', dial_code: '+995', flag: '🇬🇪', nationality: 'Georgian', digits: 9 },
    { name: 'Germany', code: 'DE', dial_code: '+49', flag: '🇩🇪', nationality: 'German', digits: 10 },
    { name: 'Ghana', code: 'GH', dial_code: '+233', flag: '🇬🇭', nationality: 'Ghanaian', digits: 9 },
    { name: 'Greece', code: 'GR', dial_code: '+30', flag: '🇬🇷', nationality: 'Greek', digits: 10 },
    { name: 'Grenada', code: 'GD', dial_code: '+1-473', flag: '🇬🇩', nationality: 'Grenadian', digits: 7 },
    { name: 'Guatemala', code: 'GT', dial_code: '+502', flag: '🇬🇹', nationality: 'Guatemalan', digits: 8 },
    { name: 'Guinea', code: 'GN', dial_code: '+224', flag: '🇬🇳', nationality: 'Guinean', digits: 9 },
    { name: 'Guinea-Bissau', code: 'GW', dial_code: '+245', flag: '🇬🇼', nationality: 'Bissau-Guinean', digits: 7 },
    { name: 'Guyana', code: 'GY', dial_code: '+592', flag: '🇬🇾', nationality: 'Guyanese', digits: 7 },
    { name: 'Haiti', code: 'HT', dial_code: '+509', flag: '🇭🇹', nationality: 'Haitian', digits: 8 },
    { name: 'Honduras', code: 'HN', dial_code: '+504', flag: '🇭🇳', nationality: 'Honduran', digits: 8 },
    { name: 'Hungary', code: 'HU', dial_code: '+36', flag: '🇭🇺', nationality: 'Hungarian', digits: 9 },
    { name: 'Iceland', code: 'IS', dial_code: '+354', flag: '🇮🇸', nationality: 'Icelander', digits: 7 },
    { name: 'India', code: 'IN', dial_code: '+91', flag: '🇮🇳', nationality: 'Indian', digits: 10 },
    { name: 'Indonesia', code: 'ID', dial_code: '+62', flag: '🇮🇩', nationality: 'Indonesian', digits: 10 },
    { name: 'Iran', code: 'IR', dial_code: '+98', flag: '🇮🇷', nationality: 'Iranian', digits: 10 },
    { name: 'Iraq', code: 'IQ', dial_code: '+964', flag: '🇮🇶', nationality: 'Iraqi', digits: 10 },
    { name: 'Ireland', code: 'IE', dial_code: '+353', flag: '🇮🇪', nationality: 'Irish', digits: 9 },
    { name: 'Israel', code: 'IL', dial_code: '+972', flag: '🇮🇱', nationality: 'Israeli', digits: 9 },
    { name: 'Italy', code: 'IT', dial_code: '+39', flag: '🇮🇹', nationality: 'Italian', digits: 10 },
    { name: 'Ivory Coast', code: 'CI', dial_code: '+225', flag: '🇨🇮', nationality: 'Ivorian', digits: 10 },
    { name: 'Jamaica', code: 'JM', dial_code: '+1-876', flag: '🇯🇲', nationality: 'Jamaican', digits: 7 },
    { name: 'Japan', code: 'JP', dial_code: '+81', flag: '🇯🇵', nationality: 'Japanese', digits: 10 },
    { name: 'Jordan', code: 'JO', dial_code: '+962', flag: '🇯🇴', nationality: 'Jordanian', digits: 9 },
    { name: 'Kazakhstan', code: 'KZ', dial_code: '+7', flag: '🇰🇿', nationality: 'Kazakhstani', digits: 10 },
    { name: 'Kenya', code: 'KE', dial_code: '+254', flag: '🇰🇪', nationality: 'Kenyan', digits: 9 },
    { name: 'Kiribati', code: 'KI', dial_code: '+686', flag: '🇰🇮', nationality: 'I-Kiribati', digits: 8 },
    { name: 'Kuwait', code: 'KW', dial_code: '+965', flag: '🇰🇼', nationality: 'Kuwaiti', digits: 8 },
    { name: 'Kyrgyzstan', code: 'KG', dial_code: '+996', flag: '🇰🇬', nationality: 'Kyrgyzstani', digits: 9 },
    { name: 'Laos', code: 'LA', dial_code: '+856', flag: '🇱🇦', nationality: 'Laotian', digits: 10 },
    { name: 'Latvia', code: 'LV', dial_code: '+371', flag: '🇱🇻', nationality: 'Latvian', digits: 8 },
    { name: 'Lebanon', code: 'LB', dial_code: '+961', flag: '🇱🇧', nationality: 'Lebanese', digits: 8 },
    { name: 'Lesotho', code: 'LS', dial_code: '+266', flag: '🇱🇸', nationality: 'Mosotho', digits: 8 },
    { name: 'Liberia', code: 'LR', dial_code: '+231', flag: '🇱🇷', nationality: 'Liberian', digits: 7 },
    { name: 'Libya', code: 'LY', dial_code: '+218', flag: '🇱🇾', nationality: 'Libyan', digits: 9 },
    { name: 'Liechtenstein', code: 'LI', dial_code: '+423', flag: '🇱🇮', nationality: 'Liechtensteiner', digits: 7 },
    { name: 'Lithuania', code: 'LT', dial_code: '+370', flag: '🇱🇹', nationality: 'Lithuanian', digits: 8 },
    { name: 'Luxembourg', code: 'LU', dial_code: '+352', flag: '🇱🇺', nationality: 'Luxembourger', digits: 9 },
    { name: 'Madagascar', code: 'MG', dial_code: '+261', flag: '🇲🇬', nationality: 'Malagasy', digits: 9 },
    { name: 'Malawi', code: 'MW', dial_code: '+265', flag: '🇲🇼', nationality: 'Malawian', digits: 9 },
    { name: 'Malaysia', code: 'MY', dial_code: '+60', flag: '🇲🇾', nationality: 'Malaysian', digits: 9 },
    { name: 'Maldives', code: 'MV', dial_code: '+960', flag: '🇲🇻', nationality: 'Maldivian', digits: 7 },
    { name: 'Mali', code: 'ML', dial_code: '+223', flag: '🇲🇱', nationality: 'Malian', digits: 8 },
    { name: 'Malta', code: 'MT', dial_code: '+356', flag: '🇲🇹', nationality: 'Maltese', digits: 8 },
    { name: 'Marshall Islands', code: 'MH', dial_code: '+692', flag: '🇲🇭', nationality: 'Marshallese', digits: 7 },
    { name: 'Mauritania', code: 'MR', dial_code: '+222', flag: '🇲🇷', nationality: 'Mauritanian', digits: 8 },
    { name: 'Mauritius', code: 'MU', dial_code: '+230', flag: '🇲🇺', nationality: 'Mauritian', digits: 7 },
    { name: 'Mexico', code: 'MX', dial_code: '+52', flag: '🇲🇽', nationality: 'Mexican', digits: 10 },
    { name: 'Micronesia', code: 'FM', dial_code: '+691', flag: '🇫🇲', nationality: 'Micronesian', digits: 7 },
    { name: 'Moldova', code: 'MD', dial_code: '+373', flag: '🇲🇩', nationality: 'Moldovan', digits: 8 },
    { name: 'Monaco', code: 'MC', dial_code: '+377', flag: '🇲🇨', nationality: 'Monégasque', digits: 8 },
    { name: 'Mongolia', code: 'MN', dial_code: '+976', flag: '🇲🇳', nationality: 'Mongolian', digits: 8 },
    { name: 'Montenegro', code: 'ME', dial_code: '+382', flag: '🇲🇪', nationality: 'Montenegrin', digits: 8 },
    { name: 'Morocco', code: 'MA', dial_code: '+212', flag: '🇲🇦', nationality: 'Moroccan', digits: 9 },
    { name: 'Mozambique', code: 'MZ', dial_code: '+258', flag: '🇲🇿', nationality: 'Mozambican', digits: 9 },
    { name: 'Myanmar', code: 'MM', dial_code: '+95', flag: '🇲🇲', nationality: 'Burmese', digits: 9 },
    { name: 'Namibia', code: 'NA', dial_code: '+264', flag: '🇳🇦', nationality: 'Namibian', digits: 9 },
    { name: 'Nauru', code: 'NR', dial_code: '+674', flag: '🇳🇷', nationality: 'Nauruan', digits: 7 },
    { name: 'Nepal', code: 'NP', dial_code: '+977', flag: '🇳🇵', nationality: 'Nepalese', digits: 10 },
    { name: 'Netherlands', code: 'NL', dial_code: '+31', flag: '🇳🇱', nationality: 'Dutch', digits: 9 },
    { name: 'New Zealand', code: 'NZ', dial_code: '+64', flag: '🇳🇿', nationality: 'New Zealander', digits: 8 },
    { name: 'Nicaragua', code: 'NI', dial_code: '+505', flag: '🇳🇮', nationality: 'Nicaraguan', digits: 8 },
    { name: 'Niger', code: 'NE', dial_code: '+227', flag: '🇳🇪', nationality: 'Nigerien', digits: 8 },
    { name: 'Nigeria', code: 'NG', dial_code: '+234', flag: '🇳🇬', nationality: 'Nigerian', digits: 10 },
    { name: 'North Korea', code: 'KP', dial_code: '+850', flag: '🇰🇵', nationality: 'North Korean', digits: 10 },
    { name: 'North Macedonia', code: 'MK', dial_code: '+389', flag: '🇲🇰', nationality: 'Macedonian', digits: 8 },
    { name: 'Norway', code: 'NO', dial_code: '+47', flag: '🇳🇴', nationality: 'Norwegian', digits: 8 },
    { name: 'Oman', code: 'OM', dial_code: '+968', flag: '🇴🇲', nationality: 'Omani', digits: 8 },
    { name: 'Pakistan', code: 'PK', dial_code: '+92', flag: '🇵🇰', nationality: 'Pakistani', digits: 10 },
    { name: 'Palau', code: 'PW', dial_code: '+680', flag: '🇵🇼', nationality: 'Palauan', digits: 7 },
    { name: 'Panama', code: 'PA', dial_code: '+507', flag: '🇵🇦', nationality: 'Panamanian', digits: 8 },
    { name: 'Papua New Guinea', code: 'PG', dial_code: '+675', flag: '🇵🇬', nationality: 'Papua New Guinean', digits: 7 },
    { name: 'Paraguay', code: 'PY', dial_code: '+595', flag: '🇵🇾', nationality: 'Paraguayan', digits: 9 },
    { name: 'Peru', code: 'PE', dial_code: '+51', flag: '🇵🇪', nationality: 'Peruvian', digits: 9 },
    { name: 'Philippines', code: 'PH', dial_code: '+63', flag: '🇵🇭', nationality: 'Filipino', digits: 10 },
    { name: 'Poland', code: 'PL', dial_code: '+48', flag: '🇵🇱', nationality: 'Pole', digits: 9 },
    { name: 'Portugal', code: 'PT', dial_code: '+351', flag: '🇵🇹', nationality: 'Portuguese', digits: 9 },
    { name: 'Qatar', code: 'QA', dial_code: '+974', flag: '🇶🇦', nationality: 'Qatari', digits: 8 },
    { name: 'Romania', code: 'RO', dial_code: '+40', flag: '🇷🇴', nationality: 'Romanian', digits: 9 },
    { name: 'Russia', code: 'RU', dial_code: '+7', flag: '🇷🇺', nationality: 'Russian', digits: 10 },
    { name: 'Rwanda', code: 'RW', dial_code: '+250', flag: '🇷🇼', nationality: 'Rwandan', digits: 9 },
    { name: 'Saint Kitts and Nevis', code: 'KN', dial_code: '+1-869', flag: '🇰🇳', nationality: 'Kittitian/Nevisian', digits: 7 },
    { name: 'Saint Lucia', code: 'LC', dial_code: '+1-758', flag: '🇱🇨', nationality: 'Saint Lucian', digits: 7 },
    { name: 'Saint Vincent and the Grenadines', code: 'VC', dial_code: '+1-784', flag: '🇻🇨', nationality: 'Saint Vincentian', digits: 7 },
    { name: 'Samoa', code: 'WS', dial_code: '+685', flag: '🇼🇸', nationality: 'Samoan', digits: 7 },
    { name: 'San Marino', code: 'SM', dial_code: '+378', flag: '🇸🇲', nationality: 'Sammarinese', digits: 10 },
    { name: 'Sao Tome and Principe', code: 'ST', dial_code: '+239', flag: '🇸🇹', nationality: 'Sao Tomean', digits: 7 },
    { name: 'Saudi Arabia', code: 'SA', dial_code: '+966', flag: '🇸🇦', nationality: 'Saudi', digits: 9 },
    { name: 'Senegal', code: 'SN', dial_code: '+221', flag: '🇸🇳', nationality: 'Senegalese', digits: 9 },
    { name: 'Serbia', code: 'RS', dial_code: '+381', flag: '🇷🇸', nationality: 'Serbian', digits: 9 },
    { name: 'Seychelles', code: 'SC', dial_code: '+248', flag: '🇸🇨', nationality: 'Seychellois', digits: 7 },
    { name: 'Sierra Leone', code: 'SL', dial_code: '+232', flag: '🇸🇱', nationality: 'Sierra Leonean', digits: 8 },
    { name: 'Singapore', code: 'SG', dial_code: '+65', flag: '🇸🇬', nationality: 'Singaporean', digits: 8 },
    { name: 'Slovakia', code: 'SK', dial_code: '+421', flag: '🇸🇰', nationality: 'Slovak', digits: 9 },
    { name: 'Slovenia', code: 'SI', dial_code: '+386', flag: '🇸🇮', nationality: 'Slovene', digits: 8 },
    { name: 'Solomon Islands', code: 'SB', dial_code: '+677', flag: '🇸🇧', nationality: 'Solomon Islander', digits: 7 },
    { name: 'Somalia', code: 'SO', dial_code: '+252', flag: '🇸🇴', nationality: 'Somali', digits: 9 },
    { name: 'South Africa', code: 'ZA', dial_code: '+27', flag: '🇿🇦', nationality: 'South African', digits: 9 },
    { name: 'South Korea', code: 'KR', dial_code: '+82', flag: '🇰🇷', nationality: 'South Korean', digits: 9 },
    { name: 'South Sudan', code: 'SS', dial_code: '+211', flag: '🇸🇸', nationality: 'South Sudanese', digits: 9 },
    { name: 'Spain', code: 'ES', dial_code: '+34', flag: '🇪🇸', nationality: 'Spaniard', digits: 9 },
    { name: 'Sri Lanka', code: 'LK', dial_code: '+94', flag: '🇱🇰', nationality: 'Sri Lankan', digits: 9 },
    { name: 'Sudan', code: 'SD', dial_code: '+249', flag: '🇸🇩', nationality: 'Sudanese', digits: 9 },
    { name: 'Suriname', code: 'SR', dial_code: '+597', flag: '🇸🇷', nationality: 'Surinamese', digits: 7 },
    { name: 'Sweden', code: 'SE', dial_code: '+46', flag: '🇸🇪', nationality: 'Swede', digits: 9 },
    { name: 'Switzerland', code: 'CH', dial_code: '+41', flag: '🇨🇭', nationality: 'Swiss', digits: 9 },
    { name: 'Syria', code: 'SY', dial_code: '+963', flag: '🇸🇾', nationality: 'Syrian', digits: 9 },
    { name: 'Taiwan', code: 'TW', dial_code: '+886', flag: '🇹🇼', nationality: 'Taiwanese', digits: 9 },
    { name: 'Tajikistan', code: 'TJ', dial_code: '+992', flag: '🇹🇯', nationality: 'Tajik', digits: 9 },
    { name: 'Tanzania', code: 'TZ', dial_code: '+255', flag: '🇹🇿', nationality: 'Tanzanian', digits: 9 },
    { name: 'Thailand', code: 'TH', dial_code: '+66', flag: '🇹🇭', nationality: 'Thai', digits: 9 },
    { name: 'Togo', code: 'TG', dial_code: '+228', flag: '🇹🇬', nationality: 'Togolese', digits: 8 },
    { name: 'Tonga', code: 'TO', dial_code: '+676', flag: '🇹🇴', nationality: 'Tongan', digits: 7 },
    { name: 'Trinidad and Tobago', code: 'TT', dial_code: '+1-868', flag: '🇹🇹', nationality: 'Trinidadian', digits: 7 },
    { name: 'Tunisia', code: 'TN', dial_code: '+216', flag: '🇹🇳', nationality: 'Tunisian', digits: 8 },
    { name: 'Turkey', code: 'TR', dial_code: '+90', flag: '🇹🇷', nationality: 'Turk', digits: 10 },
    { name: 'Turkmenistan', code: 'TM', dial_code: '+993', flag: '🇹🇲', nationality: 'Turkmen', digits: 8 },
    { name: 'Tuvalu', code: 'TV', dial_code: '+688', flag: '🇹🇻', nationality: 'Tuvaluan', digits: 5 },
    { name: 'Uganda', code: 'UG', dial_code: '+256', flag: '🇺🇬', nationality: 'Ugandan', digits: 9 },
    { name: 'Ukraine', code: 'UA', dial_code: '+380', flag: '🇺🇦', nationality: 'Ukrainian', digits: 9 },
    { name: 'United Arab Emirates', code: 'AE', dial_code: '+971', flag: '🇦🇪', nationality: 'Emirati', digits: 9 },
    { name: 'United Kingdom', code: 'GB', dial_code: '+44', flag: '🇬🇧', nationality: 'British', digits: 10 },
    { name: 'United States', code: 'US', dial_code: '+1', flag: '🇺🇸', nationality: 'American', digits: 10 },
    { name: 'Uruguay', code: 'UY', dial_code: '+598', flag: '🇺🇾', nationality: 'Uruguayan', digits: 8 },
    { name: 'Uzbekistan', code: 'UZ', dial_code: '+998', flag: '🇺🇿', nationality: 'Uzbek', digits: 9 },
    { name: 'Vanuatu', code: 'VU', dial_code: '+678', flag: '🇻🇺', nationality: 'Ni-Vanuatu', digits: 7 },
    { name: 'Vatican City', code: 'VA', dial_code: '+39', flag: '🇻🇦', nationality: 'Vatican', digits: 10 },
    { name: 'Venezuela', code: 'VE', dial_code: '+58', flag: '🇻🇪', nationality: 'Venezuelan', digits: 10 },
    { name: 'Vietnam', code: 'VN', dial_code: '+84', flag: '🇻🇳', nationality: 'Vietnamese', digits: 9 },
    { name: 'Yemen', code: 'YE', dial_code: '+967', flag: '🇾🇪', nationality: 'Yemeni', digits: 9 },
    { name: 'Zambia', code: 'ZM', dial_code: '+260', flag: '🇿🇲', nationality: 'Zambian', digits: 9 },
    { name: 'Zimbabwe', code: 'ZW', dial_code: '+263', flag: '🇿🇼', nationality: 'Zimbabwean', digits: 9 }
]
